<template>
  <section id="roadmap"  class="text-center roadmap-section py-12">
    <div class="max-width-section">
      <h2 class="mb-6">
        ROADMAP
      </h2>
      <BaseDivider class="divider mb-12"/>

      <p>The private sale will be the first stage in our journey.</p>
      <p>The pre-sale will have 500 Urban Sloths while the public sale will have 4500, during our pre-sale, we will airdrop 0.5 egld to one random holder every 10 mints until the 500 treshold is met.</p>
      <BaseTimeline :items="timelineItems"/>
    </div>
  </section>
</template>
<script>
import BaseDivider from "@/components/BaseDivider";
import BaseTimeline from "@/components/BaseTimeline";

export default {
  name: "RoadmapSection",
  components: {
    BaseDivider,
    BaseTimeline
  },
  data() {
    return {
      publicPath: process.env.BASE_URL,
      timelineItems: [
        {
          // eslint-disable-next-line no-useless-escape
          quote: "'It`s nap time!'",
          title: "NFT Staking&Royalties",
          description: "We'll set up a community  treasury just for staking rewards:\n- The community  treasury will receive 60% of the mint funds.\n- The community treasury will get 80% of the royalties generated by the secondary market\nRoyalties are the earnings generated by the NFTs' secondary market sales fees.\nPer trade, a royalty fee of 10% will be charged.\n20% of the royalties will go to the team's treasury (to fund marketing, partnerships etc)\nIn terms of our Staking System, you will earn passive income simply by keeping your Sloth in your wallet; the more you have, the better.\nawards will be distributed every two weeks or monthly, depending on how the community votes.We'll assign roles according on how many nfts you own before we start staking."
        },
        {
          title: "Charity and Donations",
          description: "You're not just purchasing nfts, you're also contributing to a worthy cause. All of the charities that will get the funds will be chosen and voted on by the community. THE PEOPLE ARE IN CONTROL. We want to provide the community the opportunity to decide who will benefit from this donation and how the funds will be distributed.",
          quote: "'I`m too lazy to stop being lazy!'"
        },
        {
          title: "NFT Airdrop",
          description: "A golden lottery ticket will be airdropped to every sloth owner.When 80% of the collection has been sold, the lottery will be drawn. with prizes starting at 100 egld",
          quote: "'No Sir! I don't like to 'Move it''"
        },
        {
          title: "We want you to have fun.",
          description: "There will be chances to win tickets to some of Europe's major festivals and city breaksWe'll let the community decide whether it'll be given away in a contest or at random.",
          quote:"'Take it easy!'"
        },
        {
          title: "Trivia Quiz",
          description: "We'll put your general knowledge skills to the test while forming friendships. We'll have 3 monthly quizzes with prizes in egld, as well as one slothzilla quiz with prizes in gaming PCs, laptops, phones, and other cutting-edge technology. Be the first to successfully answer all of the questions and walk away with the prize.",
          quote: "'Feeling philoslothical...'"
        },
        {
          title: "Exclusive Merchandise",
          description: "Sloth Couture, With your one-of-a-kind sloth, you can get exclusive products. We'll open Sloth's Merch Store for holders when 70% of the collection has been sold. You may get limited edition t-shirts, hoodies, hats, and other merchandise.",
          quote: "'Live slow!"        
        },
        {
          title: "Roadmap Update",
          description: "This is our roadmap until the Q4 of 2022, after that, we will update it with the ideas and suggestions from the holders.\nWe'll adjust the roadmap, nothing will be removed, only added. If you have any recommendations, please do not hesitate to contact us.",
          quote: "'Anytime is naptime!'"
        }
      ]
    }
  }
}
</script>

<style lang="scss">
.roadmap-section  {
  background-color: #000000;

  .divider {
    max-width: 100px;
    margin-left: auto;
    margin-right: auto;
  }

  .max-width-section {
    margin: 0 auto;
    max-width: 1000px;
    padding-left: 20px;
    padding-right: 20px;
  }
}
</style>